@Trabajo_Primer_Trimestre_Desarrollo_Entorno_Servidor_2DAW_HostAddress = http://localhost:5073

GET {{Trabajo_Primer_Trimestre_Desarrollo_Entorno_Servidor_2DAW_HostAddress}}/weatherforecast/
Accept: application/json

###
